
server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/auth/realms/myrealm
#          issuer-uri: http://localhost:8080/realms/myrealm

